### ISSUE TITLE
ClientConnectorError: Cannot connect to host 

### ISSUE THREAD

**Issue by yuv41** [yannickgloster/discord-10man#123]
Hi, im trying to run the bot on my Debian 10 machine, It boots up and works but when i run .pug it moves captains rooms and crashes
Command raised an exception: ClientConnectorError: Cannot connect to host 137.74.78.83:3000 ssl:default [Connect call failed ('137.74.78.83', 3000)]

What could be possibly the issue? 
Full Log
https://shibe.host/p2DRwh0.txt

**Comment by sawb** [comment]
Thanks for posting the solution 👍
