### ISSUE TITLE
.force_end isn't recognized by the bot

### ISSUE THREAD

**Issue by yuv41** [yannickgloster/discord-10man#125]
When sending .force_end the match is force stopped in game but the bot doesn't recognize it.
![Yo](https://shibe.host/19REK7E.png)

**Comment by iceyman** [comment]
i just did .force_end and it stopped my game ( had to run command 3 times tho ) but it didn't remove the voice channels it made for the teams
![Screenshot_37](https://user-images.githubusercontent.com/5343324/110196686-f0c91600-7e91-11eb-90d3-86971cf7f8dc.png)

**Comment by yannickgloster** [comment]
Will be fixed with move to Javascript
