### ISSUE TITLE
Discord bot doesn't recognize finished games

### ISSUE THREAD

**Issue by akkeoh** [yannickgloster/discord-10man#134]
Hi, I've setup the 10man bot with a CSGO server which works quite fine, altho I have one issue. For some reason the bot doesn't recognize the score of the game or when the match is finished. Could this be cause of a misconfiguration? Or is it a glitch?

- Bot starts queue with leaders
- Bot configures the server and sends ip+connect link
- Knife round works fine
- Match works fine

But when the match is finished nothing happens with the bot, and to be able to use the same server again i have to restart the bot.

Glad with any help at this point :)

**Comment by yannickgloster** [comment]
The bot is being rewritten into Javascript so hopefully this issue gets fixed with that
