### ISSUE TITLE
ModuleNotFoundError: No module named 'valve.rcon'

### ISSUE THREAD

**Issue by lowcardozo** [yannickgloster/discord-10man#135]
when i run the command python -m pipenv run python3 run.py, send me this error
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    import bot
  File "E:\discord-10man-master\bot.py", line 7, in <module>
    from utils.server import WebServer
  File "E:\discord-10man-master\utils\server.py", line 5, in <module>
    import valve.rcon
ModuleNotFoundError: No module named 'valve.rcon

why ? 
I hope someone helps me thanks in advance!

**Comment by yannickgloster** [comment]
have you installed all the dependencies as is listed in the wiki? Could you provide the list of all the installed dependencies?

**Comment by lowcardozo** [comment]
hello i fix it, but i have another problem i joined in the discord server to get more help! but thanks for the helping !
