### ISSUE TITLE
Look into using Intents

### ISSUE THREAD

**Issue by yannickgloster** [yannickgloster/discord-10man#38]
https://discordpy.readthedocs.io/en/latest/intents.html
https://discordpy.readthedocs.io/en/latest/intents.html#privileged-intents

**Comment by LakshyaShastri** [comment]
Can I be assigned to this

**Comment by lakshyashastri** [comment]
Can I be assigned to this @yannickgloster

**Comment by yannickgloster** [comment]
@LakshyaShastri 
Sorry, I already did this.

**Comment by lakshyashastri** [comment]
Okay, no worries
