### ISSUE TITLE
Collect Match Stats

### ISSUE THREAD

**Issue by yannickgloster** [yannickgloster/discord-10man#45]
Create a Database to store match stats.
Similar to this
![Popflash](https://i.imgur.com/hGLez9g.png)

**Comment by yannickgloster** [comment]
Could look into integrating [levels-ranks](https://forums.alliedmods.net/showthread.php?t=318782).
Ranks would be stored using level ranks, and then maybe we could make some request to the server for a player which would make a request to the database?

**Comment by apefhy** [comment]
Hi, an alternative is to use [CSGORankMeWeb](https://github.com/ToxicRevolution/CSGORankMeWeb) alongside 10man for tracking statistics and having a numbered "rank" of people.
