### ISSUE TITLE
multiple features required in the bot

### ISSUE THREAD

**Issue by thewickerman22** [yannickgloster/discord-10man#80]
1. there is no forceend command in the bot for the match
2. no command to change queue size like 2v2 1v1 etc in the bot 
3. there is no command to add spectators in the match
4. an option so tht bot dms the server ip and pass to the players only
5. command to pick/forcecaptains for the admin.
6. database for players ranks kills adr points etc

**Comment by yannickgloster** [comment]
1. You can force end the match in game but I'll create a command for it
2. I will add this
3. By spectators, do you mean GoTV or spectators in the game? @thewickerman22 
4. I will add this.
5. This was added in the latest beta release last night, this will be in the main release in a week once it has been tested. [Latest Beta](https://github.com/yannickgloster/discord-10man/releases/tag/v1.3.0-beta)
6. We will be creating our own ELO ranking system in a couple of months, we just are busy with college. In the mean time, you can use [get5_mysqlstats](https://github.com/splewis/get5#get5_mysqlstats)

**Comment by thewickerman22** [comment]
By spectators, do you mean GoTV or spectators in the game? @thewickerman22
in game spectators. once the match starts get5  wont allow spectators to join i think so we need a command to add spectators to the match
p.s i was just testing the bot. there is a live match but the bot says no live match i m getting this error in console [get5_eventapi.smx] API request failed, HTTP status code = 0

**Comment by yannickgloster** [comment]
I can add that, I'll just create a command and then when you add someone as a spectator, they will be a spectator for every server.

**Comment by thewickerman22** [comment]
i mean add and remove spectators command since while hosting a tournament need to add spectators for streaming the match

**Comment by yannickgloster** [comment]
> p.s i was just testing the bot. there is a live match but the bot says no live match i m getting this error in console [get5_eventapi.smx] API request failed, HTTP status code = 0

Join the [discord](https://discord.gg/3cNJmmc) for help but that is probably due to not having your bot port forwarded or not having steamworks installed on the server

**Comment by yannickgloster** [comment]
> i mean add and remove spectators command since while hosting a tournament need to add spectators for streaming the match

Yes I will add that

**Comment by yannickgloster** [comment]
So the features should be added to the beta version tonight and I'll update the docs this weekend. You can run the command `.help` to see the added commands once there is the new version. I'll link it here.

**Comment by thewickerman22** [comment]
thanks a lot i will give it a try

**Comment by thewickerman22** [comment]
can a cooldown feature be added if a player rage quits more than  3 mins like valve mm the bot automatically prevents the person from joining the queue again

**Comment by yannickgloster** [comment]
right now we don't track any user information but when we do we will add stuff like that. That won't be before winter December I think just because I have college

**Comment by thewickerman22** [comment]
ok np
