### ISSUE TITLE
new issues and feature request

### ISSUE THREAD

**Issue by thewickerman22** [yannickgloster/discord-10man#83]
**Describe the bug**
bot was setup for a 1v1 but after readying up the bot froze at map veto. 
![1](https://user-images.githubusercontent.com/69313521/97946165-9159dd00-1daf-11eb-8584-d4f4c90b430d.jpg)
need an option to empty the queue and delete the vc for the match

**Comment by bboychris168** [comment]
Yeh ive mentioned this to restol already. I also have the same issue. Seems to be something on the windows operation system side.

**Comment by thewickerman22** [comment]
new issues
1. when bot is set up for 2v2 bot asks to pick up in 1 2 2 2 1 format rather it shud be 1 1. actually bot shud enforce 1 2 2 2 1 only when vc has enough players.
2. bot needs a force captains command in case captains are wrongly chosen. (admins only)
3. bot needs a player replace command in case somone wants to leave the queue. (admins only)
4 once the team are drafted and map veto is goin on there shud be option for re team selection as well as map veto in case one map wronly vetod. (admins only)
5. command for emptying the queue(admin only)
6. the ready up process is meant for 60 secs but i noticed it only allows for 1-2 seconds to ready up(bug)
7. get5 check auth is not working. only linked steam ids with the dc shud be allowed but it seems everyone can join.
8. setup_match_size command is not working properly. its not changing the size of the queue vc. i set it up for 2 first and then 4 but its askin to ready up with only two players joined(bug)
9. after the bot creates two vc for the teams the players gets server muted(bug)

**Comment by yannickgloster** [comment]
1. Will fix
2. Already exists
3. Well if you just disconnect from the queue you get removed from the queue. If you disconnect after readying up, not enough people will ready up in the game and the game will cancel 
4. With the way the bot is organized, I don't think that that is possible rn. What an admin could do is user rcon to force change things or just edit the json.
5. Will look into that.
6. That is a server configuration, you need to enable `get5_check_auths 1` on the server
7. This might be because the queue is already running, I'll look into fixing this.
8. Players get server muted? I've never seen that before, could you record your screen getting to that point?

**Comment by thewickerman22** [comment]
2. how to assign captains when people join a queue instead of a pug
3. i will tell u a situation. today while doin a 5v5 pug after all readied up. the captain one one team went afk before the veto was over. the veto process was stuck and i had to restart the bot. we need a solution like either i can change captains in between veto or i can restart the queing process. coz in casual scrim people come and go in between. xD

**Comment by yannickgloster** [comment]
2. ah for a queue, I can add that then.
3. Yeah I get you, so not everyone readied up. In theory it should have kicked that person from the list. I will look into that

**Comment by thewickerman22** [comment]
3 they all readied up. two maps got vetoed and suddenly one captain got afk. either admin shud have powers to force assign a new captain or shud be able to restart the queuing process again. when i tried to restart the pug i was getting no servers available until i restarted the bot

**Comment by thewickerman22** [comment]
ok thanks
will test it now
