### ISSUE TITLE
bot server defeans the players who dont have admin roles

### ISSUE THREAD

**Issue by thewickerman22** [yannickgloster/discord-10man#90]
**Describe the bug**
as soon as bot creates vcs for teams. the players other than admins are server deafened and cannot use voice activity. i have to mannualy remove their server defean and allow voice activity

**To Reproduce**
start a pug  players this error will show when players are moved to individual vcs. 

**Expected behavior**
players shudnt be muted

**Screenshots**
https://cdn.discordapp.com/attachments/772754371938091018/776320751376138240/unknown.png
https://cdn.discordapp.com/attachments/772754371938091018/776320833056407552/unknown.png
https://cdn.discordapp.com/attachments/772754371938091018/776320913921802260/unknown.png

**Comment by yannickgloster** [comment]
@thewickerman22, What is the Muted Role you have in the first screenshot. I believe that this issue comes from that.

**Comment by thewickerman22** [comment]
removing the role fixed the issue thanks
